=== cbanh/cloud-notification-message-schema-1/cumulus_sns_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "cumulus-message",
  "description": "A cumulus SNS Message to trigger or respond to processing. The current schema only allows for single granule to be identified.",
  "type": "object",
  "properties": {
    "receivedTime": {
      "description": "Time message was received by the ingest system",
      "type":"string"
    },
    "ingestTime": {
      "description": "Time ingestion was finished by ingest system",
      "type":"string"
    },
    "deliveryTime": {
      "description": "Time message was sent to ingest system's SNS topic",
      "type":"string"
    },
    "identifier": {
      "description":"Unique identifier for the message as a whole. It is usally the senders responsibility to ensure uniqueness. This identifier can be used in response messages to provide tracability.",
      "type":"string"
    },
    "collection": {
      "description": "The collection for which these granules will belong. Could be the same as URS or some other identifier.",
      "type": "string"
    },
    "provider": {
      "description": "the name of the provider producing these files. This is informational only and is not used by the cumulus framework",
      "type": "string"
    },
    "response":{
      "description": "The response message type sent. Can be a success message or error message. Akin to both the PAN and PDRD",
      "type": "object",
      "properties": {
        "status":{
          "description":"Successful or error.",
          "type":"string",
          "enum": [
            "SUCCESS",
            "FAILURE"
          ]
        },
        "errorCode": {
          "description":"Error message. Success messages can be ignored.",
          "type":"string",
          "enum": [
            "INGEST_ERROR",
            "ARCHIVE_ERROR",
            "UNKNOWN_ERROR",
            "OTHER"
          ]
        },
        "errorMessage":{
          "description":"The message error for the failure that occured.",
          "type":"string"
        }
      },
      "required": [
          "status"
      ]
    },
    "product": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Identifier/name of the product",
          "type": "string"
        },
        "dataVersion": {
          "description": "Version of this product",
          "type": "string"
        },
        "files": {
          "description": "array of files that make up this granule",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "description": "The type of file. science files (netcdf, HDF, binary) should use the 'data' type. More can be added if need and consensus demand.",
                "type": "string",
                "enum": [
                  "data",
                  "browse",
                  "metadata",
                  "qa"
                ]
              },
              "uri": {
                "description": "the URI of the file (s3://...)",
                "type": "string"
              },
              "name": {
                "description": "The human readable filename that this file represents. ",
                "type": "string"
              },
              "checksumType": {
                "description": "Type of the checksum (e.g. md5). Optional. If no checksumType is defined for a file, it is assumed to be md5",
                "type": "string"
              },
              "checksum": {
                "description": "Checksum of the file.",
                "type": "string"
              },
              "size": {
                "description": "Size, in bytes, of the file.",
                "type": "number"
              }
            },
            "required": [
              "type",
              "uri",
              "size",
              "checksum",
              "name"
            ]
          }
        }
      },
      "required": [
        "name",
        "dataVersion",
        "files"
      ]
    }
  },
  "oneOf": [
    {"required": ["deliveryTime","collection", "identifier", "product"]},
    {"required": ["receivedTime","ingestTime","deliveryTime","collection", "response"] }
  ]
}

=== cbanh/cloud-notification-message-schema-1/samples/cumulus_sns_v4.json
{
  "provider": "PODAAC_SWOT",
  "collection": "SWOT_Prod_l2:1",
  "ingestTime":"2017-09-30T03:45:29.791198",
  "deliveryTime":"2017-09-30T03:42:29.791198",
  "receivedTime":"2017-09-30T03:42:31.634552",
  "identifier": "1234-abcd-efg0-9876",
  "response": {
    "status":"FAILURE",
    "errorCode": "INGEST_ERROR",
    "errorMessage": "File [cumulus-dev-a4d38f59-5e57-590c-a2be-58640db02d91/prod_20170926T11:30:36/production_file.nc] did not match gve checksum value."
  }
}
